services:
  frontend:
    image: irfankpm01/frontend
    ports:
      - "80:5173"
    restart: unless-stopped

  backend:
    image: irfankpm01/backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      ENV: prod
      WORKERS: 2